### ISSUE TITLE
awesome reproducible research

### ISSUE THREAD

**Issue by leipzig** [mdozmorov/bioinformatics-impact#1]
Hi, you might be interested in my RR list. Looking forward to your paper.
https://github.com/leipzig/awesome-reproducible-research

**Comment by mdozmorov** [comment]
Fantastic resource, thanks, @leipzig. Added it to https://github.com/mdozmorov/blogs/tree/master/Bioinformatics, and invited others to open issues with additional resources in the [README](https://github.com/mdozmorov/bioinformatics-impact/blob/master/README.md) file of this repository.

**Comment by mdozmorov** [comment]
Added a notion to README to look for additional resources in the closed issues
